# Generated by Django 4.1.1 on 2022-09-13 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='subscription',
            options={'ordering': ['id']},
        ),
        migrations.AddConstraint(
            model_name='subscription',
            constraint=models.UniqueConstraint(fields=('who_subscribes', 'subscribes_to'), name='unique_who_subscribes_subscribes_to'),
        ),
    ]
