# Generated by Django 2.2.19 on 2022-09-05 12:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipies', '0003_auto_20220902_1751'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ingredient',
            old_name='measurment_unit',
            new_name='measurement_unit',
        ),
    ]
