# Generated by Django 4.1.1 on 2022-09-13 18:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipies', '0007_favorite_unique_favorite_user_recipe_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='ingredientinrecipe',
            name='unique_ingredient_amount',
        ),
    ]
