# Generated by Django 4.1.1 on 2022-09-13 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipies', '0008_remove_ingredientinrecipe_unique_ingredient_amount'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='ingredientinrecipe',
            constraint=models.UniqueConstraint(fields=('ingredient', 'amount'), name='unique_ingredient_amount'),
        ),
    ]
